name: ride_sharing_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  page_transition: ^2.1.0
  sqflite: ^2.3.3+1
  json_annotation: ^4.9.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.3
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
        - asset: assets/fonts/Inter-Medium.otf
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Light.otf
        - asset: assets/fonts/Inter-Black.otf
        - asset: assets/fonts/Inter-ExtraBold.otf
        - asset: assets/fonts/Inter-ExtraLight.otf
        - asset: assets/fonts/Inter-SemiBold.otf
        - asset: assets/fonts/Inter-Thin.otf

  assets:
    - assets/drawable/
